spring:
  application:
    name: plantservice
  datasource:
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
server:
  port: 9192
